# Generated by Django 5.0.14 on 2026-06-19 21:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import sites.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=50, unique=True, verbose_name='ID do Site (Código)')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Site')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('status', models.CharField(choices=[('PLANNED', 'Planejado'), ('ACTIVE', 'Ativo'), ('MAINTENANCE', 'Em Manutenção'), ('INACTIVE', 'Inativo')], default='PLANNED', max_length=20, verbose_name='Status Operacional')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição / Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Site de Telecom',
                'verbose_name_plural': 'Sites de Telecom',
                'ordering': ['site_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('ENGINEER', 'Engenheiro'), ('TECHNICIAN', 'Técnico de Campo')], default='TECHNICIAN', max_length=20, verbose_name='Cargo / Nível de Acesso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SiteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=sites.models.site_file_upload_path, verbose_name='Arquivo Original')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição do Conteúdo')),
                ('category', models.CharField(choices=[('PDF', 'Relatório Técnico (PDF)'), ('IMAGE', 'Foto / Imagem (JPG/PNG)'), ('DWG', 'Planta AutoCAD (DWG)'), ('OTHER', 'Outros Documentos')], max_length=10, verbose_name='Categoria do Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sites.site', verbose_name='Site Vinculado')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Arquivo de Site',
                'verbose_name_plural': 'Arquivos de Sites',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
