# Generated by Django 5.0.14 on 2026-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='actual_report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Laudo Realizado'),
        ),
        migrations.AddField(
            model_name='site',
            name='actual_survey_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vistoria Realizada'),
        ),
        migrations.AddField(
            model_name='site',
            name='partner_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa Parceira'),
        ),
        migrations.AddField(
            model_name='site',
            name='planned_report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Laudo Planejado'),
        ),
        migrations.AddField(
            model_name='site',
            name='planned_survey_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vistoria Planejada'),
        ),
        migrations.AddField(
            model_name='site',
            name='scope_type',
            field=models.CharField(choices=[('LAUDO', 'Laudo Técnico'), ('PROJETO', 'Projeto'), ('OBRA', 'Obra / Instalação'), ('OUTRO', 'Outro')], default='LAUDO', max_length=20, verbose_name='Escopo do Acionamento'),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Cadastrado'), ('ACTIVE', 'Finalizado'), ('MAINTENANCE', 'Em Alerta'), ('INACTIVE', 'Prazo Vencido')], default='PLANNED', max_length=20, verbose_name='Status Operacional'),
        ),
    ]
