# Generated by Django 5.0.14 on 2026-06-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_actual_report_date_site_actual_survey_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='partner_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fornecedora de Laudo/Projeto'),
        ),
    ]
