# Generated by Django 5.0.14 on 2026-06-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_site_address_alter_site_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='access_released_date',
            field=models.DateField(blank=True, null=True, verbose_name='Acesso Liberado em'),
        ),
        migrations.AddField(
            model_name='site',
            name='access_requested_date',
            field=models.DateField(blank=True, null=True, verbose_name='Acesso Solicitado em'),
        ),
        migrations.AddField(
            model_name='site',
            name='access_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Não Iniciado'), ('REQUESTED', 'Acesso Solicitado'), ('RELEASED', 'Acesso Liberado'), ('NOT_REQUIRED', 'Acesso Não Necessário')], default='NOT_REQUIRED', max_length=20, verbose_name='Situação do Acesso'),
        ),
        migrations.AddField(
            model_name='site',
            name='reschedule_count',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Replanejamentos'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('ROOFTOP', 'Rooftop'), ('GREENFIELD', 'Greenfield'), ('OUTRO', 'Outros'), ('NENHUM', 'Não exige liberação')], default='NENHUM', max_length=20, verbose_name='Tipo de Estrutura'),
        ),
    ]
