# Generated by Django 5.0.14 on 2026-06-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_site_access_released_date_site_access_requested_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='stages_status',
            field=models.JSONField(blank=True, default=dict, verbose_name='Status das Etapas'),
        ),
        migrations.AlterField(
            model_name='site',
            name='scope_type',
            field=models.CharField(choices=[('LAUDOS', 'Laudos'), ('INSTALACAO', 'Instalação'), ('INFRA', 'Infra'), ('FABRICA', 'Fabrica')], default='LAUDOS', max_length=20, verbose_name='Escopo do Acionamento'),
        ),
    ]
