# Generated by Django 5.0.14 on 2026-06-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_site_stages_status_alter_site_scope_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='access_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Não Iniciado'), ('REQUESTED', 'Acesso Solicitado'), ('RELEASED', 'Acesso Liberado'), ('NOT_REQUIRED', 'Acesso Não Necessário')], default='NOT_STARTED', max_length=20, verbose_name='Situação do Acesso'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('ROOFTOP', 'Rooftop'), ('GREENFIELD', 'Greenfield'), ('INDOOR', 'Indoor'), ('STREET', 'Street')], default='ROOFTOP', max_length=20, verbose_name='Tipo de Estrutura'),
        ),
    ]
