# Generated by Django 5.0.14 on 2026-06-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_site_access_status_alter_site_site_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='ID do Site (Código)'),
        ),
    ]
