# Generated by Django 5.0.14 on 2026-06-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_alter_site_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='operator',
            field=models.CharField(blank=True, choices=[('VIVO', 'Vivo'), ('TIM', 'Tim'), ('CLARO', 'Claro'), ('OI', 'Oi'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Operadora'),
        ),
    ]
