# Generated by Django 5.0.14 on 2026-06-24 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_site_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRescheduleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_planned_survey_date', models.DateField(blank=True, null=True, verbose_name='Vistoria Planejada Anterior')),
                ('new_planned_survey_date', models.DateField(blank=True, null=True, verbose_name='Nova Vistoria Planejada')),
                ('previous_planned_report_date', models.DateField(blank=True, null=True, verbose_name='Laudo Planejado Anterior')),
                ('new_planned_report_date', models.DateField(blank=True, null=True, verbose_name='Novo Laudo Planejado')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo do Replanejamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_histories', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Histórico de Replanejamento',
                'verbose_name_plural': 'Históricos de Replanejamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
