# Generated by Django 5.0.14 on 2026-06-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_sitereschedulehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Anotação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Nota do Calendário',
                'verbose_name_plural': 'Notas do Calendário',
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
