# Generated by Django 5.0.14 on 2026-06-28 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_site_uf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitereschedulehistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Histórico de Replanejamento (Legado)', 'verbose_name_plural': 'Históricos de Replanejamento (Legado)'},
        ),
        migrations.CreateModel(
            name='SiteStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('LAUDOS', 'Laudos'), ('INSTALACAO', 'Instalação'), ('INFRA', 'Infra'), ('FABRICA', 'Fabrica')], max_length=20, verbose_name='Escopo')),
                ('stage_name', models.CharField(max_length=100, verbose_name='Nome da Etapa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Data Planejada')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Data Realizada')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('DONE', 'Concluído'), ('SKIPPED', 'Ignorado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Etapa do Site',
                'verbose_name_plural': 'Etapas dos Sites',
                'ordering': ['site', 'order'],
                'unique_together': {('site', 'stage_name')},
            },
        ),
        migrations.CreateModel(
            name='SiteStageReschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_date', models.DateField(blank=True, null=True, verbose_name='Data Anterior')),
                ('new_date', models.DateField(blank=True, null=True, verbose_name='Nova Data')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='sites.sitestage', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Replanejamento de Etapa',
                'verbose_name_plural': 'Replanejamentos de Etapas',
                'ordering': ['-created_at'],
            },
        ),
    ]
