# Generated by Django 5.0.14 on 2026-06-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0017_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Foto de Perfil (Base64)'),
        ),
    ]
