# Generated by Django 5.0.14 on 2026-06-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0018_user_profile_picture_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_view',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('sites', 'Sites'), ('calendario', 'Calendário'), ('analytics', 'Desempenho')], default='dashboard', max_length=20, verbose_name='Visualização Padrão'),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_email_notifications',
            field=models.BooleanField(default=True, verbose_name='Receber notificações por e-mail'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10, verbose_name='Preferência de Tema'),
        ),
    ]
