# Generated by Django 5.0.14 on 2026-07-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0020_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='target_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do Ativo'),
        ),
    ]
