# Generated by Django 5.0.14 on 2026-07-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0021_systemlog_target_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='scope_type',
            field=models.CharField(choices=[('LAUDOS', 'Laudos'), ('INSTALACAO', 'Instalação'), ('INFRA', 'Infra'), ('FABRICA', 'Fabrica'), ('PROJETOS', 'Projetos')], default='LAUDOS', max_length=20, verbose_name='Escopo do Acionamento'),
        ),
        migrations.AlterField(
            model_name='sitestage',
            name='scope_type',
            field=models.CharField(choices=[('LAUDOS', 'Laudos'), ('INSTALACAO', 'Instalação'), ('INFRA', 'Infra'), ('FABRICA', 'Fabrica'), ('PROJETOS', 'Projetos')], max_length=20, verbose_name='Escopo'),
        ),
    ]
