# Generated by Django 5.0.14 on 2026-07-02 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0022_alter_site_scope_type_alter_sitestage_scope_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(verbose_name='Número da Revisão')),
                ('request_date', models.DateField(verbose_name='Data da Solicitação')),
                ('receive_date', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo / Observações da Revisão')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando Retorno'), ('RECEIVED', 'Revisão Recebida')], default='PENDING', max_length=20, verbose_name='Status da Revisão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='sites.sitestage', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Revisão de Etapa',
                'verbose_name_plural': 'Revisões de Etapas',
                'ordering': ['revision_number'],
            },
        ),
    ]
